### ISSUE TITLE
Domain Manager (API Gateway)

### ISSUE THREAD

**Issue by cbschuld** [Open-SL/serverless-permission-generator#19]
### Description

In order to use the serverless domain manager for serverless.com you need some additional IAM permissions.  The team on that plugin was kind enough to denote them here:

https://www.npmjs.com/package/serverless-domain-manager

It would be wonderful to extend this tooling to have a checkbox for the Domain Manager.

I am happy to submit a PR but I am not sure covering an extension like this is something you want to cover?

### Special Thanks

This is a really neat generator tool; I appreciate everyone who has worked on it!

**Comment by nadunindunil** [comment]
Hi @cbschuld ,
Thank you very much for your kind words. 🎉
You can definitely add a PR with suggesting code changes.
When we implement the change,
We can divide the required permission to AWS service level and then add checkboxes.
ex: a separate box for route53.
Please do let me know if you have any questions.

**Comment by cbschuld** [comment]
@nadunindunil - thanks I pushed up the PR

**Comment by nadunindunil** [comment]
Hi @cbschuld ,
This is great. Thank you very much. We will push these changes with our next release.

**Comment by nadunindunil** [comment]
closing the issue 
Thank you @cbschuld
