### ISSUE TITLE
Deployment fails when "Serverless Warmup Plugin" is used

### ISSUE THREAD

**Issue by joshuaquek** [Open-SL/serverless-permission-generator#22]
### Prerequisites

* [ ✅] Are you running the latest version?
* [✅ ] Did you check the debugging guide?
* [ ✅] Did you check this issue in Issue section?
* [ ✅] Are you reporting to the correct repository?
* [ ✅] Did you perform a cursory search?

For more information, see the [CONTRIBUTING](CONTRIBUTING.md) guide.

### Description

Is there a way to also factor in the Serverless Warmup Lambda deployment? 
https://github.com/juanjoDiaz/serverless-plugin-warmup

### Steps to Reproduce

Create a new project and import in the Serverless Warmup Plugin

**Expected behavior:** [What you expected to happen]

Lambda and Warmup lambda gets deployed

**Actual behavior:** [What actually happened]

Deployment fails 

![image](https://user-images.githubusercontent.com/5335756/106876306-88600b00-6712-11eb-9241-1515c114b247.png)

### Versions

Latest version

**Comment by joshuaquek** [comment]
Resolved this by adding `events:PutRule` and `events:PutTargets` to my resource `arn:aws:events:ap-southeast-1:334923857064:rule/expressjsserverless-v1-*`

In the policy, it looks like this:
```json
{
    "Effect": "Allow",
    "Action": [
        "events:DescribeRule",
        "events:PutRule",
        "events:PutTargets"
    ],
    "Resource": [
        "arn:aws:events:ap-southeast-1:334923857064:rule/expressjsserverless-v1-*"
    ]
}
```

_Note: user id was changed above to a fake one for privacy purposes._

**Comment by nadunindunil** [comment]
Hi @joshuaquek ,
Thank you very much for the feedback. We will add these to the application asap. 
One question regarding the warming a lambda **that is not related to this repo**,
is it expensive?
did you compare prices between the actual running server and warming up lambda function prices? 
This is not related to the issue and I was wondering about prices. 😇

**Comment by joshuaquek** [comment]
Hi @nadunindunil, for now it seems to cost 3 times less than if one were to use Route53 health checks to keep a lambda warm (prevents cold start delays). 

USD$1.50 versus USD$0.51

Managed to find a reference to the cost calculation from the plugin's repo here: https://github.com/juanjoDiaz/serverless-plugin-warmup/issues/179

**Comment by joshuaquek** [comment]
Adding a more direct answer by the creator of the plugin, which I've managed to find:

https://github.com/juanjoDiaz/serverless-plugin-warmup#cost

**Comment by joshuaquek** [comment]
Just an update, when I tried to do a rollback of the serverless deployed lambda, I received this error:

![image](https://user-images.githubusercontent.com/5335756/107326688-d5fbbf80-6ae6-11eb-8a78-33c4f118e7f9.png)

I fixed it by adding `events:RemoveTargets` too, apart from `events:PutRule` and `events:PutTargets`. 

That section of the policy now looks like this (updated):

```json
{
    "Effect": "Allow",
    "Action": [
        "events:DescribeRule",
        "events:PutRule",
        "events:DeleteRule",
        "events:PutTargets",
        "events:RemoveTargets"
    ],
    "Resource": [
        "arn:aws:events:<region>:<account>:rule/expressjsserverless-v1-*"
    ]
}
```

**Comment by nadunindunil** [comment]
Hi @joshuaquek ,
First, sorry for the late reply.
Thank you very much for the feedback. I'll add those details to the application.

**Comment by joshuaquek** [comment]
Great! hoping to see it soon implemented. Thank you for taking this into consideration. I have been using this tool for over 10+ different deployments already

**Comment by nadunindunil** [comment]
this was added in #28
please let me know if you face further issues
