### ISSUE TITLE
Missing generated permissions

### ISSUE THREAD

**Issue by Lerer** [Open-SL/serverless-permission-generator#23]
### Prerequisites

* [x] Are you running the latest version?
* [ ] Did you check the debugging guide?
* [x] Did you check this issue in Issue section?
* [x] Are you reporting to the correct repository?
* [ ] Did you perform a cursory search?

For more information, see the [CONTRIBUTING](CONTRIBUTING.md) guide.

### Description

The generated policy was not enough to deploy and had to add few more items manually

I had to add the following manually when pasting to AWS:
```json
{
  "Effect": "Allow",
  "Action": "logs:PutSubscriptionFilter",
  "Resource": [
    "arn:aws:logs:<Region>:<Account ID>:log-group:/aws/lambda/*",
    "arn:aws:logs:<Region>:<Account ID>:log-group:/aws/api-gateway/*"
  ]
},
{
  "Effect": "Allow",
  "Action": "lambda:CreateEventSourceMapping",
  "Resource": "*"
}
```       

As well, when using role per lambda plugin, i had to change the:
`arn:aws:iam::<Account ID>:role/<Service>-<stage>-<region>-lambdaRole` with `arn:aws:iam::<Account ID>:role/<Service>-<stage>-<region>-*`

**Comment by nadunindunil** [comment]
Hi @Lerer ,
Thank you very much for the feedback
Could you please explain the reasons to request `logs:PutSubscriptionFilter` and `lambda:CreateEventSourceMapping` permissions ?

**Comment by Lerer** [comment]
Hi,
I tried to deploy using serverless with lambda triggered from SQS. Using permissions generated here it failed. The error messages lead me to add what I mentioned above (manually) in order to make it a policy fit for deployment

**Comment by nadunindunil** [comment]
@Lerer 
This was applied in #25 
However, I need resources of the `lambda:CreateEventSourceMapping` in order to apply the least priviledges.

**Comment by nadunindunil** [comment]
Hi @Lerer,
I added `lambda:CreateEventSourceMapping` as well in the above PR.
Let me know if you think otherwise.

and closing the issues since all the concerns were addressed.
