### ISSUE TITLE
s3:DeleteBucketPolicy missing 

### ISSUE THREAD

**Issue by qube13** [Open-SL/serverless-permission-generator#9]
On removing a project with a user that has the policy created by the generator, the s3:DeleteBucketPolicy is missing and therefore I get an error when trying to remove the cloudformation stack. 

Steps to reproduce: 

1. Create a policy for a project on https://open-sl.github.io/serverless-permission-generator/ 
2. Use that policy to deploy the project without entering a deployment-bucket in the serverless.yml 
3. Remove that service

**Comment by nadunindunil** [comment]
Hi @qube13 ,
Thank you very much for the information. I will pick this issue for the next release. 
Could you please let us know if you find more missing policies so that we can improve the policy generation?

**Comment by nadunindunil** [comment]
**How to fix the issue:**
input the `s3:DeleteBucketPolicy` permission in this file https://github.com/Open-SL/serverless-permission-generator/blob/master/src/generator/index.js in both `s3Generator` and `generator`.

**Comment by nadunindunil** [comment]
Hi @qube13 ,
submitted a PR with a fix. please see #17

**Comment by nadunindunil** [comment]
Close the issue with PR merge
